#!/usr/bin/env python3
"""Isolated gateway + real Chutni + generated multilingual folder, streamed UI turn.

The optional live URL receives only requests generated by this isolated test.
It never queries the installed app's folders, memories, chats, or logs.
"""
import argparse
import json
import os
from pathlib import Path
import shlex
import socket
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

ROOT = Path(__file__).resolve().parents[1]
BUILD = ROOT / os.environ.get('BUILD_DIR', 'build')
parser = argparse.ArgumentParser()
parser.add_argument('--backend', action='store_true')
parser.add_argument('--port', type=int)
parser.add_argument('--live-backend-url')
parser.add_argument('--expect-failure', action='store_true')
parser.add_argument('--output', type=Path)
args, _ = parser.parse_known_args()


def tokens(text):
    return (len(text.encode('utf-8')) + 1) // 2 + 32


def log(row):
    with open(os.environ['SAMOSA_CONTEXT_TEST_LOG'], 'a') as handle:
        handle.write(json.dumps(row) + '\n')


class Backend(BaseHTTPRequestHandler):
    def log_message(self, *_): pass
    def reply(self, data, status=200):
        raw = json.dumps(data).encode()
        self.send_response(status)
        self.send_header('Content-Length', str(len(raw)))
        self.end_headers()
        try: self.wfile.write(raw)
        except (BrokenPipeError, ConnectionResetError): pass

    def do_GET(self):
        if self.path == '/props':
            return self.reply({'default_generation_settings': {'n_ctx': 8192}})
        self.reply({'ready': True})

    def do_POST(self):
        raw = self.rfile.read(int(self.headers['Content-Length']))
        try: body = json.loads(raw.decode('utf-8'))
        except (UnicodeError, ValueError):
            log({'path': self.path, 'error': 'invalid_utf8_or_json'})
            return self.reply({'error': 'invalid UTF-8 JSON'}, 400)
        messages = body.get('messages', [])
        live = os.environ.get('SAMOSA_CONTEXT_TEST_LIVE')
        # Native indexing summaries are a fixture, so the live check focuses
        # on actual overview/compaction and synthesis rather than 80 T5 jobs.
        review = any('Summarize this folder evidence section' in m.get('content', '') for m in messages)
        final = any('Answer from the folder/file action evidence' in m.get('content', '') for m in messages)
        if live and (self.path in ('/apply-template', '/tokenize') or review or final):
            request = urllib.request.Request(live + self.path, data=raw, headers={'Content-Type': 'application/json'})
            try:
                with urllib.request.urlopen(request, timeout=240) as response:
                    content = response.read()
                    # Streamed responses must stay streamed, without a JSON
                    # wrapper or an extra final-answer-only test shortcut.
                    self.send_response(response.status)
                    self.send_header('Content-Type', response.headers.get('Content-Type', 'application/json'))
                    self.send_header('Content-Length', str(len(content)))
                    self.end_headers(); self.wfile.write(content)
                    log({'path': self.path, 'review': review, 'final': final, 'status': response.status})
            except urllib.error.HTTPError as error:
                log({'path': self.path, 'review': review, 'final': final, 'status': error.code})
                self.reply(json.loads(error.read()), error.code)
            return
        if self.path == '/apply-template':
            return self.reply({'prompt': '\n'.join(m['role'] + ': ' + m['content'] for m in messages) + '\nassistant:'})
        if self.path == '/tokenize': return self.reply({'tokens': [1] * tokens(body['content'])})
        if self.path != '/v1/chat/completions': return self.reply({}, 404)
        prompt = '\n'.join(m['role'] + ': ' + m['content'] for m in messages) + '\nassistant:'
        prompt_tokens = tokens(prompt)
        if (review or final) and prompt_tokens + body.get('max_tokens', 0) > 8192:
            log({'error': 'overflow', 'prompt_tokens': prompt_tokens})
            return self.reply({'error': 'context exceeded'}, 400)
        log({'path': self.path, 'review': review, 'final': final, 'prompt_tokens': prompt_tokens,
             'max_tokens': body.get('max_tokens'), 'valid_utf8': True})
        content = 'Generated orchard irrigation, coastal navigation, and pottery records.'
        if body.get('stream'):
            data = 'data: ' + json.dumps({'choices': [{'delta': {'content': content}}]}) + '\n\ndata: [DONE]\n\n'
            self.send_response(200); self.send_header('Content-Type', 'text/event-stream')
            self.send_header('Content-Length', str(len(data.encode()))); self.end_headers(); self.wfile.write(data.encode())
        else: self.reply({'choices': [{'message': {'content': content}, 'finish_reason': 'stop'}]})


if args.backend:
    ThreadingHTTPServer(('127.0.0.1', args.port), Backend).serve_forever()
    sys.exit(0)


def free_port():
    with socket.socket() as sock:
        sock.bind(('127.0.0.1', 0)); return sock.getsockname()[1]


with tempfile.TemporaryDirectory(prefix='samosa-context-e2e-') as temporary:
    base = Path(temporary); app_home = base/'home'; source = base/'source'
    app_home.mkdir(); source.mkdir()
    # The opening sample contains real UTF-8 of different widths. The fixed
    # evidence byte budget must never end halfway through a code point.
    for i in range(80):
        category = ('orchard irrigation', 'coastal navigation', 'pottery')[i % 3]
        prefix = category + '\n'
        prefix += 'A' * ((1 - len(prefix.encode())) % 9)
        text = prefix + 'é漢😀' * 200 + '\n'
        (source/f'record-{i:03d}.txt').write_text(text)
    engine = base/'backend'; model = base/'model.gguf'
    engine.write_text('#!/bin/sh\nexec ' + shlex.quote(sys.executable) + ' ' + shlex.quote(str(Path(__file__).resolve())) + ' --backend "$@"\n')
    engine.chmod(0o755); model.write_bytes(b'generated-model-fixture')
    decision = base/'decision'
    decision.write_text('#!' + sys.executable + '\nimport json,sys\n'
        'request=json.load(open(sys.argv[sys.argv.index("--request")+1]))\n'
        'sources=[{"number":s["number"],"choice":"plausible","score":1} for s in request["sources"]]\n'
        'print(json.dumps({"version":1,"scope":"folder","actions":["overview"],"sources":sources}))\n')
    decision.chmod(0o755)
    public, private = free_port(), free_port()
    env = dict(os.environ, SAMOSA_HOME=str(app_home), SAMOSA_READ_CACHE_DIR=str(app_home/'read-cache'), CHUTNI_HOME=str(base/'chutni'),
        SAMOSA_PORT=str(public), SAMOSA_BACKEND_PORT=str(private), SAMOSA_LLAMA_CTX='8192',
        SAMOSA_BONSAI_SERVER=str(engine), SAMOSA_ORNITH_MODEL=str(model),
        SAMOSA_APP_HTML=str(ROOT/'assets/app.html'), SAMOSA_APP_LIFECYCLE='0',
        SAMOSA_DEFER_PENDING_MEMORY='1', SAMOSA_CHUTNI_SERVICE=str(BUILD/'chutni-mcp'),
        SAMOSA_FS=str(BUILD/'samosa-fs'), SAMOSA_EXTRACT=str(BUILD/'samosa-extract'),
        SAMOSA_DECISION=str(decision), SAMOSA_CONTEXT_TEST_LOG=str(base/'model-metrics.jsonl'))
    if args.live_backend_url: env['SAMOSA_CONTEXT_TEST_LIVE'] = args.live_backend_url
    with open(base/'gateway.log', 'w') as output:
        gateway = subprocess.Popen([str(BUILD/'samosa-gateway')], env=env, stdout=output, stderr=output)
    try:
        token = ''
        def request(path, body=None):
            data = json.dumps(body).encode() if body is not None else None
            try:
                return urllib.request.urlopen(urllib.request.Request(f'http://127.0.0.1:{public}'+path,
                    data=data, headers={'X-Samosa-Token': token, 'Content-Type': 'application/json'}), timeout=900)
            except urllib.error.HTTPError as error:
                raise RuntimeError((error.code, error.read().decode())) from error
        for _ in range(200):
            try:
                with request('/healthz') as response: health = json.load(response)
                if health['ready']: break
            except urllib.error.URLError: pass
            time.sleep(.05)
        else: raise RuntimeError((base/'gateway.log').read_text())
        token = (app_home/'run/ui-token').read_text().strip()
        with request('/v1/chutni/preflight', {'kind':'folder','roots':[{'path':str(source)}]}) as response: preflight = json.load(response)
        with request('/v1/chutni/scopes', {'preflight_id':preflight['preflight_id'],
            'policy_fingerprint':preflight['policy_fingerprint'],'display_name':'Generated multilingual records'}) as response: created = json.load(response)
        scope = created['scope_id']
        for _ in range(200):
            with request('/v1/chutni/scopes/'+scope) as response: state = json.load(response)
            if state['state'] in ('ready','ready_partial'): break
            assert state['state'] != 'failed', state
            time.sleep(.1)
        else: raise RuntimeError(state)
        started = time.monotonic(); events = []; answer = ''; errors = []
        with request('/v1/chat/completions', {'model':health['model'], 'stream':True,'max_tokens':8192,
            'conversation_id':'generated-context-e2e',
            'model_id':health['backend'],'model_version':health['model_version'],
            'chat_template_kwargs':{'enable_thinking':False},
            'messages':[{'role':'system','content':'Today is Sunday. Answer the latest question naturally.'},
                        {'role':'user','content':'What is this directory about?'}],
            'directory_context':{'scope_id':scope}}) as response:
            for line in response:
                if not line.startswith(b'data: ') or line.strip() == b'data: [DONE]': continue
                event = json.loads(line[6:]); events.append(event)
                if 'error' in event: errors.append(event['error'])
                for choice in event.get('choices',[]):
                    delta = choice.get('delta',{})
                    answer += delta.get('content','') or ''
                    if args.live_backend_url and delta.get('file_activity'):
                        print(json.dumps({'seconds':round(time.monotonic()-started,2),'activity':delta['file_activity']['message']}),flush=True)
        metrics = [json.loads(row) for row in (base/'model-metrics.jsonl').read_text().splitlines()]
        result = {'seconds':round(time.monotonic()-started,2),'files':state.get('files_indexed'),
            'errors':errors,'answer':answer,'model_metrics':metrics,'events':events}
        if args.output:
            args.output.parent.mkdir(parents=True,exist_ok=True); args.output.write_text(json.dumps(result,indent=2)+'\n')
        print(json.dumps({k:v for k,v in result.items() if k not in ('events','model_metrics')}),flush=True)
        if args.expect_failure:
            assert errors and errors[0]['code']=='folder_context_budget_failed'
            assert not any(row.get('review') or row.get('final') for row in metrics)
        else:
            assert not errors and answer, result
            assert not any(row.get('error') for row in metrics), metrics
            assert any(row.get('review') for row in metrics), 'Compaction was not exercised'
            assert any(row.get('final') for row in metrics), 'No final synthesis request'
    finally:
        gateway.terminate()
        try: gateway.wait(timeout=10)
        except subprocess.TimeoutExpired: gateway.kill(); gateway.wait()
