// Real UI acceptance for the explicitly isolated, generated search fixture.
import {createRequire} from 'node:module';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.SAMOSA_PLAYWRIGHT_ROOT+'/node_modules/playwright');
const base=process.env.SAMOSA_TEST_URL, home=process.env.SAMOSA_HOME, root=process.env.SAMOSA_TYPE_FIXTURE;
assert(base && !base.includes(':8642') && home && !home.endsWith('/.samosa') && root);
const out=process.env.SAMOSA_TEST_EVIDENCE; fs.mkdirSync(out,{recursive:true});
const rows=[]; const record=row=>{rows.push(row); fs.writeFileSync(out+'/results.json',JSON.stringify(rows,null,2)); console.log(JSON.stringify(row));};
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
page.on('pageerror',e=>record({stage:'page_error',error:e.message}));
let saved;
page.on('response',async response=>{if(response.url().endsWith('/v1/jobs/decision/start') && response.ok()) saved=await response.json();});
try {
 await page.goto(base); await page.locator('#navJobs').waitFor({state:'visible'});
 if(await page.locator('#webConsentNo').isVisible()) await page.locator('#webConsentNo').click();
 await page.locator('#navJobs').click();
 await page.locator('#jobFolder').fill(root);
 const goal='find all documents that look like I539 in this folder.';
 await page.locator('#jobGoal').fill(goal); await page.locator('#jobRun').click();
 await page.waitForFunction(()=>document.querySelectorAll('.job-progress-table tbody tr').length>=15,null,{timeout:180000});
 await page.waitForFunction(()=>[...document.querySelectorAll('.job-progress-table tbody tr')].some(row=>row.children[1].textContent==='Likely match'),null,{timeout:180000});
 const progress=await page.locator('.job-progress-table tbody tr').evaluateAll(rows=>rows.map(row=>[...row.children].map(cell=>cell.textContent)));
 assert.equal(new Set(progress.map(row=>row[0])).size,progress.length,'Progress duplicated file rows');
 record({stage:'live_progress',rows:progress,counts:await page.locator('.job-progress-count').innerText()});
 await page.locator('.job-progress-count').evaluate(el=>el.scrollIntoView({block:'start'}));
 await page.screenshot({path:out+'/progress-table.png',fullPage:true});
 await page.waitForFunction(()=>!document.querySelector('#jobRun').disabled,null,{timeout:600000});
 await page.locator('#jobResult').waitFor({state:'visible'});
 assert.equal(await page.locator('#jobResultLabel').innerText(),'Search results');
 await page.waitForFunction(()=>!!document.querySelector('.job-decision-results'),null,{timeout:10000});
 const filter=page.getByLabel('Filter files'); await filter.selectOption('all');
 const files=await page.locator('.job-decision-list tr').evaluateAll(rows=>rows.map(row=>({path:row.children[1].querySelector('strong')?.textContent,status:row.children[2]?.textContent})));
 assert.equal(files.length,15);
 const matches=files.filter(row=>row.status==='Likely match').map(row=>row.path).sort();
 assert(matches.includes('scan-042.pdf') && matches.includes('scan-087.pdf'));
 assert(matches.every(path=>['scan-042.pdf','scan-087.pdf','raster-301.pdf'].includes(path)),'Unrelated file admitted as a match');
 assert.equal(files.find(row=>row.path==='supplement-061.pdf').status,'No match in preview');
 assert.equal(files.find(row=>row.path==='I539-unreadable.bin').status,'Needs review');
 record({stage:'checked_files',files});
 await page.locator('.job-decision-results').evaluate(el=>el.scrollIntoView({block:'start'}));
 await page.screenshot({path:out+'/checked-files-table.png',fullPage:true});
 await filter.selectOption('likely');
 const box=page.locator('.job-decision-list input[type=checkbox]').first(); await box.check();
 await page.waitForFunction(()=>document.querySelector('#jobSelectionStatus').textContent.includes('saved'),null,{timeout:10000});
 const selected=await box.getAttribute('aria-label');
 assert(saved?.job_id);
 const token=fs.readFileSync(home+'/run/ui-token','utf8').trim();
 const result=await page.request.get(base+'/v1/jobs/decision/result?job_id='+encodeURIComponent(saved.job_id),{headers:{'X-Samosa-Token':token}});
 assert.equal((await result.json()).selected_paths.length,1);
 const beforeMatches=saved.result.items.filter(item=>item.decision==='match').map(item=>item.path).sort();
 const nextResponse=page.waitForResponse(response=>response.url().endsWith('/v1/jobs/decision/next') && response.ok(),{timeout:180000});
 await page.locator('#jobCheckSelected').click();
 const deeper=await (await nextResponse).json();
 assert.deepEqual(deeper.result.search_intent,saved.result.search_intent);
 assert.deepEqual(deeper.result.items.filter(item=>item.decision==='match').map(item=>item.path).sort(),beforeMatches);
 assert.equal(deeper.selected_paths.length,1);
 assert.equal(deeper.result.items.find(item=>item.path===deeper.selected_paths[0]).excerpt_chars,3200);
 record({stage:'selected_deepen',job_id:saved.job_id,selected_paths:deeper.selected_paths,matches:beforeMatches});
 await page.locator('#jobCheckSelected').waitFor({state:'visible'});
 await page.reload(); await page.locator('#navJobs').click();
 await page.getByText('Recent work',{exact:true}).click();
 const history=page.locator('.job-history-row').filter({hasText:root}).filter({hasText:goal}).first();
 await history.getByRole('button',{name:'View saved run'}).click();
 await page.locator('.job-decision-list input[type=checkbox]').first().waitFor();
 assert.equal(await page.locator('.job-decision-list input[type=checkbox]').first().isChecked(),true);
 assert.equal(await page.locator('.job-decision-list input[type=checkbox]').first().getAttribute('aria-label'),selected);
 await page.getByLabel('Filter files').selectOption('all');
 await page.getByText('Recent work',{exact:true}).click();
 await page.setViewportSize({width:390,height:844});
 await page.locator('.job-decision-results').evaluate(el=>el.scrollIntoView({block:'start'}));
 const tableBounds=await page.locator('.job-decision-results table').boundingBox();
 assert(tableBounds.x>=0 && tableBounds.x+tableBounds.width<=390,'Narrow table exceeds the viewport');
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Narrow viewport clips content');
 await page.screenshot({path:out+'/narrow-table.png',fullPage:true});
 record({stage:'passed',job_id:saved.job_id,selected});
 assert(!rows.some(row=>row.stage==='page_error'));
} catch(error) {record({stage:'failed',error:error.stack});process.exitCode=1;} finally {await browser.close();}
